version: '2.1'

services:
  go:
    image: dev-registry.bll-i.co.uk/brightlocal/golang-1.11:latest
    hostname: go
    restart: on-failure
    user: jenkins
    volumes:
      - ../.:/home/jenkins/go/src/github.com/BrightLocal/MySQLBackup
